### ISSUE TITLE
optionalPrecondition is required

### ISSUE THREAD

**Issue by trungniantic** [authzed/authzed-node#33]
## How to reproduce
Run the following code

```
client.writeRelationships({
            // optionalPreconditions: [],
            updates: [{
                relationship: {
                    relation: "reader",
                    resource: v1.ObjectReference.create({
                        objectType: "page",
                        objectId: "page1",
                    }),
                    subject: v1.SubjectReference.create({
                        object: v1.ObjectReference.create({
                            objectType: "user",
                            objectId: "user1,
                        })
                    }),
                },
                operation: v1.RelationshipUpdate_Operation.TOUCH
            }]
        }, (err, data) => {
            if (err) {
                console.log('error writing relationship to authorization service', err)
            } else {
                console.log('success')
            }
        })
```

gives me the following error
```error writing relationship to authorization service Error: 13 INTERNAL: Request message serialization failure: Cannot read properties of undefined (reading 'length')
    at Object.callErrorFromStatus (/Users/trungvu/dev/epos/portal/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/trungvu/dev/epos/portal/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/Users/trungvu/dev/epos/portal/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/Users/trungvu/dev/epos/portal/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /Users/trungvu/dev/epos/portal/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: "Request message serialization failure: Cannot read properties of undefined (reading 'length')",
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
```

Adding 
```
            optionalPreconditions: [],
```

fixes it

## Expectatio

Optional parameter should not be required. Otherwise remove the optional in the name

**Comment by samkim** [comment]
Did some digging and was able to arrive at a conclusion. TL;DR use the `.create` helpers on Request objects.

So for the above example, something like:
```
const request =  WriteRelationshipsRequest.create({
       updates: [{
                relationship: {
                ...
      ])
      // optionalPreconditions is actually optional
})
client.writeRelationships(request);
```

Repeated fields being required params is by design in protobuf-ts, with reasoning explained here: https://github.com/timostamm/protobuf-ts/issues/294#issuecomment-1107450171

For now, I'll update our docs and examples to use `create` consistently. Good news is that support for the `optional` proto descriptor recently was released (https://github.com/grpc/grpc-node/releases/tag/grpc-tools%401.11.2) so we have the option to make parameters truly optional for future APIs.
